name: Add theme
description: Add your port to the Vague Theme collection
title: New theme for <app>
body:
  - type: input
    attributes:
      label: Link to theme repo
    validations:
      required: true
  - type: dropdown
    id: issue-type
    attributes:
      label: What would you like to do with your repo?
      description: If moved into the org, you will be added as a maintainer
      multiple: false
      options:
        - Transfer my repo into the org
        - Duplicate (clone) my repo into the org
        - Keep my repo under my personal account
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
    validations:
      required: false
