name: Add theme
description: Add new port to the Vague Theme collection
title: New theme for <app>
body:
  - type: input
    attributes:
      label: Link to theme repo
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
    validations:
      required: false
