name: Theme request
description: Suggest a new theme
title: Theme request for <app>
body:
  - type: input
    attributes:
      label: Link to app
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Would you be willing to work on this?
      options:
        - label: Sure
  - type: textarea
    attributes:
      label: Additional information
    validations:
      required: false
